spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/
    username: ok
    password: ok
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_catalog: dev_write_company
        dialect: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: false
    show-sql: true
  liquibase:
    change-log: migration/master.yml
    default-schema: dev_write_company
    parameters:
      readSchema: dev_read_company
      writeSchema: dev_write_company
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth.test.briolink.net/auth/realms/briolink/protocol/openid-connect/certs
dgs:
  graphql:
    path: /
cloud:
  aws:
    stack:
      auto: false
app:
  aws:
    s3:
      name: briolink
event:
  publisher:
    sns-name: bl-network-dev.fifo
