logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  error:
    include-stacktrace: always
dgs:
  graphql:
    introspection:
      enabled: true
spring:
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth.dev.briolink.com/auth/realms/briolink/protocol/openid-connect/certs
app:
  app-endpoints:
    companyservice: http://192.168.0.23:8090/
    locationservice: http://192.168.0.60:8070/
permission-service:
  api:
    url: http://192.168.0.60:8200
    version: 1
