logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://${env.DB_HOST:localhost}:${env.DB_PORT:5432}/local_company
app:
  app-endpoints:
    companyservice: http://192.168.0.23:8090/
    locationservice: http://192.168.0.60:8070/
permission-service:
  api:
    url: http://192.168.0.60:8200
    version: 1
