logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  jpa:
    show-sql: true
app:
  app-endpoints:
    companyservice: http://192.168.0.23:8090/
location-service:
  api:
    url: http://192.168.0.23:8070/
    version: 1