server:
  port: 8085
spring:
  profiles:
    active: ${env.spring_profiles_active:local}
  datasource:
    url: jdbc:postgresql://${env.DB_HOST:localhost}:${env.DB_PORT:5432}/${env.spring_profiles_active}_company
    username: ${env.DB_USER:root}
    password: ${env.DB_PASSWORD:root}
    hikari:
      idle-timeout: 20000
      minimum-idle: 1
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        metadata_builder_contributor: com.briolink.lib.common.jpa.Functions
        jdbc:
          batch_size: 60
    generate-ddl: false
    show-sql: false
cloud:
  aws:
    stack:
      auto: false
app:
  app-endpoints:
    companyservice: http://companyservice-service.${env.spring_profiles_active}.svc.cluster.local:8080/
    connection: http://connection-service.${env.spring_profiles_active}.svc.cluster.local:8080/
    expverification: http://exp-verification-service.${env.spring_profiles_active}.svc.cluster.local:8080/
    user: http://user-service.${env.spring_profiles_active}.svc.cluster.local:8080/
event:
  listener:
    sqs-name: bl-network-${env.spring_profiles_active}-company-service.fifo
  publisher:
    sns-name: bl-network-${env.spring_profiles_active}.fifo
permission-service:
  api:
    url: http://permission-service.${env.spring_profiles_active}.svc.cluster.local/
    version: 1
location-service:
  api:
    url: http://location-service.${env.spring_profiles_active}.svc.cluster.local/
    version: 1
sync-service:
  api:
    url: http://sync-service.${env.spring_profiles_active}.svc.cluster.local/
    version: 1
