logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://${env.DB_HOST:localhost}:${env.DB_PORT:5432}/local_company
app:
  app-endpoints:
    companyservice: http://192.168.0.60:8090/
    expverification: http://localhost:8010/
location-service:
  api:
    url: http://192.168.0.60:8070/
    version: 1
sync-service:
  api:
    url: http://192.168.0.60:8400/
    version: 1
permission-service:
  api:
    url: http://192.168.0.60:8200
    version: 1
dictionary-service:
  api:
  url: http://192.168.0.60:8060/
  version: 1