server:
  port: 8086
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_catalog: test_read_user
        dialect: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: false
    show-sql: true
cloud:
  aws:
    stack:
      auto: false
event:
  listener:
    enabled: true
    sqs-name: bl-network-dev-company-service.fifo
